### PR TITLE
Use strict Base64 encoding to fix base64 encoding/netty issue

### PR DESCRIPTION
**Pull request by msblum**
## Pull Request Checklist

**Is this in reference to an existing issue?**
#58 
#### General

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [ ] RuboCop passes

- [ ] Existing tests pass 

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

#### Purpose
Use strict Base64 encoding to fix base64 encoding/netty issue

### CODE REVIEW

**Comment by sstarcher** [comment]
can you resolve the conflicts

**Comment by majormoses** [comment]
@msblum can you rebase please?

**Comment by majormoses** [comment]
@msblum if I don't release in the next 24 hours please ping me.

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-elasticsearch/versions/1.3.0

**Pull request merged**
