### PR TITLE
Update metrics-es-node.rb to perform version check

### PR DESCRIPTION
**Pull request by cstockton**
Use the same version check as the other checks.

### CODE REVIEW

**Comment by analytically** [comment]
Awesome, thanks for your contribution. Would you be able to cover this in a simple test spec?

**Comment by cstockton** [comment]
Not very familiar with ruby- if you point me to the current tests for this project I can try to copy one to give it some coverage. I didn't see any tests when I looked.

**Comment by cstockton** [comment]
@analytically - Added a fix for a pretty severe issue that may catch larger installs of ES off guard.

**Comment by analytically** [comment]
Thanks, is that fix compatible with ES < 2.0?

**Comment by cstockton** [comment]
@analytically We are running ES 1.7.1 and it works there.

**Comment by analytically** [comment]
Mind adding an entry to the changelog? Then I'll merge and release a new version.

**Comment by cstockton** [comment]
@analytically https://github.com/cstockton/sensu-plugins-elasticsearch/commit/fc657c107e0f377af3dcd921c7d5904bdddbaf3b

**Pull request merged**
