### PR TITLE
Add parameters for elasticsearch auth

### PR DESCRIPTION
**Pull request by pedroluislopez**

### CODE REVIEW

**Comment by tas50** [comment]
Can you take a look at the rubocop failures in travis?

**Comment by pedroluislopez** [comment]
Ok, now it works.

**Comment by mattyjones** [comment]
@pedroluislopez 

Can you update the CHANGELOG for this as well.

@tas50  I think this should go to 0.1.0, thoughts?

**Comment by tas50** [comment]
0.2.0 is prob the best bet for this

**Pull request merged**
