### PR TITLE
Leveraging the elasticsearch gem.

### PR DESCRIPTION
**Pull request by brendangibat**
This adds elasticsearch query functionality, at least for a few basic cases but could be extended easily to as needed in a few other ways. I'm currently using it like this in sensu: 

check-es-query-count.rb -h elasticsearch.service.consul -q '*' --invert --types some_type -d 'log-index-%Y.%m.%d' --minutes-previous 30 -p 9200 -c 1 -w 100

I could also move the other checks and metrics over to the gem.

### CODE REVIEW

**Comment by mattyjones** [comment]
@brendangibat   A couple of quick things off the bat.  Code you please do a rebase as I have merged in several changes since your fork.  Also all runtime dependencies must be hard pinned.  Just as I pin my production chef cookbooks, we pin runtime dependencies.

Could you also please update the CHANGELOG to include these new files and the README with the files and the file headers to include sample commands.

I would be glad to take a look at these though and then look at possibly incorporating this functionality into the other checks.

Thanks for all this!

**Comment by brendangibat** [comment]
Sure thing! I wanted to get an initial PR in to begin the conversation. This is something that's been useful but there's a lot of room in it for improvements. I'll include your requests as well as the Travis CI failures I'm seeing above on ruby 2.x environments.

**Comment by mattyjones** [comment]
@brendangibat   Rubocop is a very unhappy camper. ;p  Can you start with a `rubocop -a` which will auto fix a lot of this crap and then see where you are at.  If you have any questions, let me know.

Thanks

**Comment by scalp42** [comment]
@brendangibat any chance you can run Rubocop?

**Comment by mxk1235** [comment]
this would be great.  when can you merge?

**Comment by brendangibat** [comment]
Alright I've dropped the ball on this PR. It's been a lot of use to us and I think others would like it as well - It's great to integrate querying an elasticsearch watcher index to avoid duplicating notification systems with sensu and to get team members to go to kibana, find a query they like, then push a sensu check of what they expect. I've got time this week to update this. Sorry @mxk1235 !

**Comment by mxk1235** [comment]
no worries.  at this moment, i am just trying to pull in the script into our sensu check repo without using the gem, but in general i think it would be great if this were available.

**Comment by sstarcher** [comment]
@brendangibat could we get this pull request finished up?

**Comment by mxk1235** [comment]
+1.  still looking forward to it.

**Comment by brendangibat** [comment]
Alright I've updated according to the requests and it's passing checks as of this comment

**Pull request merged**
