### PR TITLE
more disable options for metrics-es-node-graphite.rb

### PR DESCRIPTION
**Pull request by terjesannum**

### CODE REVIEW

**Comment by majormoses** [comment]
@terjesannum thanks for the contribution, I wonder if it might be better to a single option to blacklist some metrics rather than a bunch of options as this becomes more flexible later. This pattern is followed in the redis metric checks.

**Comment by terjesannum** [comment]
I agree with that, but I didn't want to break any backward compatibility with this change. So I added those options while I where working with it, but the important change here is really just to don't output non-numeric metrics from the indices stats.

**Comment by majormoses** [comment]
Keeping backwards compatibility here is trivial just add one or more options with the defaults being proposed. If needed you can have indices_blacklist, http_blacklist, etc. I am not supportive of adding a bunch of options when it seems like a blacklist is a better approach. It enables more flexibility and will be more future proof to ES adding new ones that break hence more options.

**Comment by majormoses** [comment]
@eheydrick if you feel otherwise I am ok with this I just don't want to bring in some bubble gum when what we really need is cement.

**Comment by majormoses** [comment]
If am missing something and backwards compatibility is more difficult then I would prefer to do things right and do a major release here.

**Comment by majormoses** [comment]
@terjesannum also you need to rebase to fix conflicts

**Comment by majormoses** [comment]
@terjesannum any chance of picking this back up?

**Comment by majormoses** [comment]
@terjesannum last ping before closing

**Comment by majormoses** [comment]
closing due to inactivity

**Pull request closed without merging**
