### PR TITLE
Fix check-es-shard-allocation-status.rb for Elasticsearch 5.x compati…

### PR DESCRIPTION
**Pull request by Evesy**
…bility

## Pull Request Checklist

**Is this in reference to an existing issue?**
This fixes issue #66 

#### General

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [x] RuboCop passes

- [x] Existing tests pass 

#### Purpose

This fixes the check-es-shard-allocation-status.rb check on Elasticsearch 5.x versions.

#### Known Compatablity Issues

This change is backwards compatible with previous Elasticsearch versions.

### CODE REVIEW

**Comment by Evesy** [comment]
@majormoses New PR for allocation fix

**Comment by majormoses** [comment]
relates to: https://github.com/sensu-plugins/sensu-plugins-elasticsearch/pull/67

**Comment by majormoses** [comment]
@Evesy need a rebase please

**Comment by Evesy** [comment]
@majormoses Sorted!

**Comment by majormoses** [comment]
@Evesy an an issue and ping me if I dont release in the next 24 hours.

**Comment by majormoses** [comment]
released as 1.2.0

**Pull request merged**
