### PR TITLE
[WIP] Add Shield support to plugin

### PR DESCRIPTION
**Pull request by nakulpathak3**
## Adds shield support to the plugin

Issue - https://github.com/sensu-plugins/sensu-plugins-elasticsearch/issues/36

### Questions

- [ ] Is the general approach of adding it as a command line option okay with you guys?
- [ ] Is anyone aware of the changes needed for this in /bin/check-es-query-exists.rb and /bin/check-es-query-count.rb for this to work?

#### General

- [ ] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [ ] Binstubs are created if needed

- [ ] RuboCop passes

- [ ] Existing tests pass

### CODE REVIEW

**Comment by eheydrick** [comment]
I think we should pull the common options into a common library that all the plugins include.

**Comment by nakulpathak3** [comment]
Yeah sure, that's a good idea. I'll update the PR

**Comment by nakulpathak3** [comment]
Also, could you look at the options I asked in the PR description? Thanks

**Comment by nakulpathak3** [comment]
It's been a while but I'm gonna try to implement the refactor into a common library in the next few weeks :)

**Pull request closed without merging**
